export enum PublicRoutes {
  home = "/",
  articles = "/articles",
  articleDetail = "/articles/:slug",
  categories = "/categories",
  categoryDetail = "/categories/:slug",
  tags = "/tags",
  tagDetail = "/tags/:slug",
  search = "/search",
  about = "/about",
  contact = "/contact",
  privacy = "/privacy",
  terms = "/terms",
  offline = "/offline",
}
