import type { CollectionConfig } from "payload";
import { anyone, requireCapability } from "../access";
import { auditAfterChange, auditAfterDelete } from "../hooks/audit";
import { generateBlurPlaceholder } from "../hooks/media-blur";

export const Media: CollectionConfig = {
  slug: "media",
  admin: {
    group: "Content",
    defaultColumns: ["filename", "alt", "usageCount", "updatedAt"],
  },
  access: {
    read: anyone,
    create: requireCapability("media:upload"),
    update: requireCapability("media:upload"),
    delete: requireCapability("media:delete"),
  },
  upload: {
    staticDir: "media",
    mimeTypes: ["image/jpeg", "image/png", "image/webp", "image/gif"],
    // Focal point + crop drive smart cropping for the fixed-ratio sizes below.
    focalPoint: true,
    crop: true,
    adminThumbnail: "thumbnail",
    // Convert the stored original to WebP for a smaller, next-gen payload.
    // Trade-off: an animated GIF is flattened to a static first-frame WebP —
    // Payload has no per-mime conversion gate, so we can't skip GIF at config
    // level. Acceptable for v1 (editorial rarely ships animated GIFs); the
    // alternative of keeping GIF originals loses the JPEG→WebP storage win the
    // acceptance criteria require. Revisit with a per-file beforeChange pipeline
    // if animated GIFs become a real need.
    formatOptions: {
      format: "webp",
      options: { quality: 82 },
    },
    // Cap the stored original so a 6000px camera export doesn't sit in R2 at
    // full size. `withoutEnlargement` keeps small images untouched.
    resizeOptions: {
      width: 2560,
      height: 2560,
      fit: "inside",
      withoutEnlargement: true,
    },
    // Pre-generated responsive variants (via sharp). Names map to how the
    // public UI uses images: list thumbnails, grid/featured cards, wide heros,
    // and a 1200×630 OpenGraph crop for social/link previews.
    imageSizes: [
      { name: "thumbnail", width: 400, height: 300, position: "centre" },
      { name: "card", width: 768, height: 576, position: "centre" },
      { name: "wide", width: 1600, height: 900, position: "centre" },
      { name: "og", width: 1200, height: 630, position: "centre" },
    ],
  },
  fields: [
    {
      name: "alt",
      type: "text",
      required: true,
    },
    {
      name: "caption",
      type: "text",
    },
    {
      name: "credit",
      type: "text",
    },
    {
      name: "usageCount",
      type: "number",
      defaultValue: 0,
      admin: { readOnly: true },
    },
    {
      // Tiny (~16px) base64 WebP data URI used as a blur-up placeholder by
      // next/image. Generated by the beforeChange hook on upload; never edited
      // by hand.
      name: "blurDataUrl",
      type: "text",
      admin: {
        readOnly: true,
        hidden: true,
      },
    },
  ],
  hooks: {
    beforeChange: [generateBlurPlaceholder],
    afterChange: [auditAfterChange("media")],
    afterDelete: [auditAfterDelete("media")],
  },
};
